# Generated by Django 5.2.6 on 2025-09-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('jobseeker', 'Job Seeker')], default='jobseeker', max_length=20),
        ),
    ]
