# Generated by Django 5.2.6 on 2025-10-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cover_later',
            new_name='cover_letter',
        ),
    ]
